---
    javascripts: 
    - base: 
      - prototype
      - effects
      - dragdrop
      - controls
      - application
    - secondary:
      - multifileup
    stylesheets: 
    - base: 
      - estilo
      - forms