---
    javascripts: 
    - base: 
      - jquery
      - jquery-ui
      - jrails
      - effects
      - dragdrop
      - controls
      - application
      - jquery.form
    stylesheets: 
    - base: 
      - estilo
      - forms
      - jquery-ui-1.8.9.custom
      
