---
    javascripts: 
    - base: 
      - jquery
      - jquery-ui
      - jrails
      - jquery.form
      - jquery.MultiFile.pack
      - application
    stylesheets: 
    - base: 
      - estilo
      - forms
      - jquery-ui-1.8.9.custom
