# Configuration options can be accessed as
# configatron.site_name

development: &local
    site_name: Control de asuntos
    site_namemobile: Control de asuntos
    site_url: asuntos
    
    company_name: redleon.net
    admin_email: admin@localhost
    
    support_name: Control de asuntos
    support_email: admin@localhost
    
    site_envnote: Local Server
    status_terminado: 10
    envia_email: true
    

production:
    site_name: Control de asuntos
    site_namemobile: Control de asuntos
    site_url: ausuntos
    
    company_name: redleon.net
    admin_email: admin@localhost
    
    support_name: Control de asuntos
    support_email: admin@localhost
    
    site_envnote: Production Server
    
    status_terminado: 10
    envia_email: false
    
  
staging:
  <<: *local

test:
  <<: *local
